# AdaMTV 90s ITV-style cue dot
video_path: /root/.local/share/ersatztv/templates/graphics-elements/motion/cue-dot.webm
location: TopRight
horizontal_margin_percent: 1
vertical_margin_percent: 1
scale: true
scale_width_percent: 4
start_seconds: {{ MediaItem_Duration.TotalSeconds - 10 }}
end_behavior: disappear
z_index: 100
